Repository NamelessMC/Nameless, pull requests merged in 2021-11, with the labels that each got.

#2474 New UpgradeScript class to make upgrade scripts cleaner
  core/autoload.php
  core/classes/Misc/UpgradeScript.php
  modules/Core/pages/panel/upgrade.php
Labels: duplicate

#2483 Added, Updated & Improved Swedish Translations
  CONTRIBUTORS.md
  custom/languages/SwedishSE/admin.php
  custom/languages/SwedishSE/errors.php
  custom/languages/SwedishSE/general.php
  custom/languages/SwedishSE/installer.php
  custom/languages/SwedishSE/moderator.php
  custom/languages/SwedishSE/table.php
  custom/languages/SwedishSE/time.php
  custom/languages/SwedishSE/user.php
  custom/languages/SwedishSE/version.php
  modules/Cookie Consent/language/SwedishSE/cookie.php
  modules/Discord Integration/language/SwedishSE/discord_integration.php
  modules/Forum/language/SwedishSE/forum.php
Labels: translation

#2508 Dynamic event listener methods
  core/autoload.php
  core/classes/Events/EventHandler.php
  core/classes/Events/Listener.php
  modules/Core/hooks/DeleteUserHook.php
  modules/Core/hooks/ValidateHook.php
  modules/Forum/hooks/DeleteUserForumHook.php
Labels: enhancement

#2512 Minor corrections in Slovak translation
  custom/languages/Slovak/admin.php
  modules/Forum/language/Slovak/forum.php
Labels: translation
