Repository NamelessMC/Nameless, pull requests merged in 2021-05, with the labels that each got.

#2259 Added feature of receiving timezone on registration
  custom/templates/DefaultRevamp/js/core/core.js
  custom/templates/DefaultRevamp/register.tpl
  modules/Core/pages/register.php
Labels: enhancement

#2265 Update japanese translations.
  custom/languages/Japanese/admin.php
  custom/languages/Japanese/api.php
  custom/languages/Japanese/emails.php
  custom/languages/Japanese/errors.php
  custom/languages/Japanese/general.php
  custom/languages/Japanese/installer.php
  custom/languages/Japanese/log.php
  custom/languages/Japanese/moderator.php
  custom/languages/Japanese/table.php
  custom/languages/Japanese/time.php
  custom/languages/Japanese/user.php
  custom/languages/Japanese/version.php
  modules/Forum/language/Japanese/forum.php
Labels: translation

#2193 design modern
  core/includes/smarty/debug.tpl
Labels: design

#2268 Update Chinese (Simplified) translations
  custom/languages/Chinese(Simplified)/admin.php
  custom/languages/Chinese(Simplified)/api.php
  custom/languages/Chinese(Simplified)/emails.php
  custom/languages/Chinese(Simplified)/errors.php
  custom/languages/Chinese(Simplified)/general.php
  custom/languages/Chinese(Simplified)/installer.php
  custom/languages/Chinese(Simplified)/log.php
  custom/languages/Chinese(Simplified)/moderator.php
  custom/languages/Chinese(Simplified)/table.php
  custom/languages/Chinese(Simplified)/time.php
  custom/languages/Chinese(Simplified)/user.php
  custom/languages/Chinese(Simplified)/version.php
Labels: translation

#2273 Added default recipient value
  custom/templates/DefaultRevamp/user/new_message.tpl
Labels: bug

#2276 Renamed canViewACP to canViewStaffCP
  core/classes/User.php
  core/init.php
  core/templates/navbar.php
  modules/Core/pages/panel/auth.php
  modules/Core/pages/panel/users_edit.php
  modules/Core/pages/panel/users_punishments.php
  modules/Core/pages/profile.php
  modules/Core/pages/user/messaging.php
  modules/Forum/pages/forum/spam.php
Labels: enhancement

#2264 Add placeholderapi support + configuration + leaderboards
  README.md
  core/classes/Announcements.php
  core/classes/AvatarSource.php
  core/classes/Placeholders.php
  core/classes/Queries.php
  core/classes/User.php
  core/includes/updates/200-pr9.php
  core/init.php
  core/installation/views/includes/site_initialize.php
  custom/languages/Chinese(Simplified)/admin.php
  custom/languages/Chinese/admin.php
  custom/languages/Czech/admin.php
  custom/languages/Dutch/admin.php
  custom/languages/EnglishUK/admin.php
  custom/languages/EnglishUK/general.php
  custom/languages/EnglishUK/user.php
  custom/languages/EnglishUS/admin.php
  custom/languages/French/admin.php
  custom/languages/German/admin.php
  custom/languages/Greek/admin.php
  custom/languages/Italian/admin.php
  custom/languages/Japanese/admin.php
  custom/languages/Lithuanian/admin.php
  custom/languages/Norwegian/admin.php
  custom/languages/Polish/admin.php
  custom/languages/Portuguese/admin.php
  custom/languages/Romanian/admin.php
  custom/languages/Russian/admin.php
  custom/languages/Slovak/admin.php
  custom/languages/Spanish/admin.php
  custom/languages/SpanishES/admin.php
  custom/languages/SwedishSE/admin.php
  custom/languages/Turkish/admin.php
  custom/panel_templates/Default/core/announcements.tpl
  custom/panel_templates/Default/core/announcements_form.tpl
  custom/panel_templates/Default/core/api_endpoints.tpl
  custom/panel_templates/Default/core/placeholders.tpl
  custom/panel_templates/Default/core/placeholders_leaderboard.tpl
  custom/panel_templates/Default/template.php
  custom/templates/DefaultRevamp/leaderboards.tpl
  custom/templates/DefaultRevamp/profile.tpl
  custom/templates/DefaultRevamp/user/placeholders.tpl
  modules/Core/includes/endpoints/ServerInfoEndpoint.php
  modules/Core/module.php
  modules/Core/pages/leaderboards.php
  modules/Core/pages/panel/announcements.php
  modules/Core/pages/panel/placeholders.php
  modules/Core/pages/profile.php
  modules/Core/pages/user/placeholders.php
  modules/Forum/pages/forum/view_topic.php
Labels: enhancement

#2278 Update Slovak translation
  custom/languages/Slovak/admin.php
  custom/languages/Slovak/installer.php
  modules/Forum/language/Slovak/forum.php
Labels: translation
