Repository NamelessMC/Nameless, pull requests merged in 2021-03, with the labels that each got.

#2198 add charset option to PDO dsn
  core/classes/DB.php
Labels: awaiting-reply, bug

#2200 Rework captcha system and add Recaptcha 3
  core/classes/CaptchaBase.php
  core/includes/updates/200-pr9.php
  custom/panel_templates/Default/core/registration.tpl
  custom/templates/DefaultRevamp/contact.tpl
  custom/templates/DefaultRevamp/login.tpl
  custom/templates/DefaultRevamp/register.tpl
  modules/Core/classes/Recaptcha2.php
  modules/Core/classes/Recaptcha3.php
  modules/Core/classes/hCaptcha.php
  modules/Core/init.php
  modules/Core/module.php
  modules/Core/pages/contact.php
  modules/Core/pages/login.php
  modules/Core/pages/panel/registration.php
  modules/Core/pages/register.php
Labels: enhancement

#2194 Error handling revamp
  core/assets/plugins/prism/prism.css
  core/assets/plugins/prism/prism.js
  core/classes/DB.php
  core/classes/ErrorHandler.php
  core/classes/ExternalMCQuery.php
  core/classes/MCAssoc.php
  core/classes/Report.php
  core/init.php
  core/installation/views/steps/admin_account_setup.php
  core/templates/frontend_init.php
  error.php
  error.tpl
  index.php
  modules/Core/module.php
  modules/Core/pages/api/v2/index.php
  modules/Core/pages/authme_connector.php
  modules/Core/pages/complete_signup.php
  modules/Core/pages/panel/announcements.php
  modules/Core/pages/panel/emails_errors.php
  modules/Core/pages/panel/hooks.php
  modules/Core/pages/panel/minecraft_server_banners.php
  modules/Core/pages/panel/minecraft_servers.php
  modules/Core/pages/panel/pages.php
  modules/Core/pages/panel/panel_templates.php
  modules/Core/pages/register.php
  modules/Core/pages/user/messaging.php
  modules/Core/pages/user/settings.php
  modules/Core/widgets/StatsWidget.php
  modules/Forum/pages/forum/delete.php
  modules/Forum/pages/forum/delete_post.php
  modules/Forum/pages/forum/edit.php
  modules/Forum/pages/forum/lock.php
  modules/Forum/pages/forum/merge.php
  modules/Forum/pages/forum/move.php
  modules/Forum/pages/forum/new_topic.php
  modules/Forum/pages/forum/view_topic.php
  modules/Forum/pages/panel/forums.php
  modules/Forum/pages/panel/labels.php
Labels: design, enhancement
