Repository NamelessMC/Nameless, pull requests merged in 2022-12, with the labels that each got.

#3136 StaffCP performance improvements
  modules/Core/collections/panel/RecentPunishments.php
  modules/Core/collections/panel/RecentReports.php
  modules/Core/collections/panel/RecentUsers.php
  modules/Core/module.php
  modules/Core/pages/panel/index.php
  modules/Forum/module.php
Labels: enhancement

#3141 Dcoument backport policy in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: meta

#3135 Delete replies to a spammer's topic
  modules/Forum/pages/forum/spam.php
Labels: enhancement

#3144 Allow all tinymce valid_children when admin
  core/classes/Core/Input.php
Labels: bug
