Repository NamelessMC/Nameless, pull requests merged in 2022-10, with the labels that each got.

#3080 Update TFA page to use a post request to disable TFA
  custom/templates/DefaultRevamp/user/tfa.tpl
  modules/Core/pages/user/settings.php
Labels: hacktoberfest-accepted

#3101 Return redirect when punishing users
  modules/Core/pages/panel/users_punishments.php
Labels: enhancement, hacktoberfest-accepted

#3076 Allow browser scripts to bypass force_2fa redirects
  core/init.php
  modules/Core/pages/user/settings.php
Labels: bug, hacktoberfest-accepted

#3103 Fix oauth bypasses validation & banned checks
  modules/Core/pages/oauth.php
Labels: bug, security, hacktoberfest-accepted

#3105 Page reload fix
  modules/Core/pages/panel/api.php
  modules/Core/pages/panel/registration.php
  modules/Core/pages/panel/social_media.php
  modules/Discord Integration/pages/panel/discord.php
Labels: hacktoberfest-accepted

#3108 Fix update available alerts on frontend
  modules/Core/module.php
Labels: bug, hacktoberfest-accepted

#3097 Add ability to change password of users via StaffCP
  custom/languages/en_UK.json
  custom/panel_templates/Default/core/users_edit.tpl
  modules/Core/pages/panel/users_edit.php
Labels: enhancement

#3107 Add limit setting to latest posts widget
  custom/panel_templates/Default/forum/widgets/latest_posts.tpl
  modules/Forum/language/en_UK.json
  modules/Forum/widgets/LatestPostsWidget.php
  modules/Forum/widgets/admin/latest_posts.php
Labels: enhancement, hacktoberfest-accepted

#3100 Allow members to reset their avatar
  custom/languages/en_UK.json
  custom/templates/DefaultRevamp/user/settings.tpl
  modules/Core/pages/user/settings.php
Labels: enhancement, hacktoberfest-accepted

#3088 Fix TinyMCE spoiler plugin url
  core/classes/Core/Input.php
Labels: bug
