Repository NamelessMC/Nameless, pull requests merged in 2022-02, with the labels that each got.

#2570 OAuth register/login/linking!
  composer.json
  composer.lock
  core/classes/Core/User.php
  core/classes/Database/Queries.php
  core/classes/Misc/OAuth.php
  core/includes/updates/200-pr12.php
  core/init.php
  custom/languages/EnglishUK/admin.php
  custom/languages/EnglishUK/general.php
  custom/languages/EnglishUK/user.php
  custom/panel_templates/Default/core/registration.tpl
  custom/panel_templates/Default/core/users_oauth.tpl
  custom/templates/DefaultRevamp/login.tpl
  custom/templates/DefaultRevamp/register.tpl
  custom/templates/DefaultRevamp/user/oauth.tpl
  modules/Core/hooks/DeleteUserHook.php
  modules/Core/hooks/ValidateHook.php
  modules/Core/module.php
  modules/Core/pages/login.php
  modules/Core/pages/oauth.php
  modules/Core/pages/panel/registration.php
  modules/Core/pages/panel/users_edit.php
  modules/Core/pages/panel/users_oauth.php
  modules/Core/pages/register.php
  modules/Core/pages/user/oauth.php
Labels: enhancement, discussion

#2600 Russian translation update
  custom/languages/EnglishUK/moderator.php
  custom/languages/Russian/admin.php
  custom/languages/Russian/general.php
  custom/languages/Russian/installer.php
  custom/languages/Russian/moderator.php
  custom/languages/Russian/user.php
Labels: translation

#2604 Select menu
  custom/languages/Chinese(Simplified)/admin.php
  custom/languages/Chinese/admin.php
  custom/languages/Czech/admin.php
  custom/languages/Danish/admin.php
  custom/languages/Dutch/admin.php
  custom/languages/EnglishUK/admin.php
  custom/languages/EnglishUS/admin.php
  custom/languages/French/admin.php
  custom/languages/German/admin.php
  custom/languages/Greek/admin.php
  custom/languages/Italian/admin.php
  custom/languages/Japanese/admin.php
  custom/languages/Lithuanian/admin.php
  custom/languages/Norwegian/admin.php
  custom/languages/Polish/admin.php
  custom/languages/Portuguese/admin.php
  custom/languages/Romanian/admin.php
  custom/languages/Russian/admin.php
  custom/languages/Slovak/admin.php
  custom/languages/Spanish/admin.php
  custom/languages/SpanishES/admin.php
  custom/languages/SwedishSE/admin.php
  custom/languages/Thai/admin.php
  custom/languages/Turkish/admin.php
  custom/panel_templates/Default/core/users_edit.tpl
  custom/panel_templates/Default/forum/forums_edit.tpl
  custom/panel_templates/Default/forum/forums_new_step_2.tpl
  custom/panel_templates/Default/forum/labels_edit.tpl
  custom/panel_templates/Default/forum/labels_new.tpl
  custom/panel_templates/Default/template.php
  modules/Core/pages/panel/users_edit.php
  modules/Forum/pages/panel/forums.php
Labels: enhancement
