Repository NamelessMC/Nameless, pull requests merged in 2022-11, with the labels that each got.

#3096 Add createWebhookEndpoint
  custom/languages/en_UK.json
  modules/Core/classes/Misc/CoreApiErrors.php
  modules/Core/includes/endpoints/CreateWebhooksEndpoint.php
Labels: enhancement, hacktoberfest-accepted

#3073 Add new webhook events for profile posts and profile post replies
  custom/languages/en_UK.json
  modules/Core/module.php
  modules/Core/pages/profile.php
Labels: enhancement, hacktoberfest-accepted

#3123 Fix ROOT_PATH in cli installer
  dev/scripts/cli_install.php
Labels: bug

#3117 Add Finnish language
  core/classes/Core/Language.php
  custom/languages/fi_FI.json
  dev/scripts/create_lang.py
  modules/Cookie Consent/language/fi_FI.json
  modules/Discord Integration/language/fi_FI.json
  modules/Forum/language/fi_FI.json
Labels: translation

#3124 Update forum + topic latest post when a user is marked as spam
  modules/Forum/pages/forum/spam.php
Labels: enhancement
