Repository NamelessMC/Nameless, pull requests merged in 2023-01, with the labels that each got.

#3153 Fix fallback to default template not working
  core/templates/backend_init.php
  core/templates/frontend_init.php
Labels: bug

#3160 Docker: Workaround for yarn cache directory permission issue
  docker-compose.yaml
Labels: bug

#3161 Add instructions on how to disable portal page to template
  custom/templates/DefaultRevamp/portal.tpl
  modules/Core/pages/portal.php
Labels: enhancement

#3163 Change exception page Prism theme to One Light
  core/assets/plugins/prism/prism_light_atom.css
  core/assets/plugins/prism/prism_light_coy.css
  core/classes/Misc/ErrorHandler.php
  core/includes/error.tpl
Labels: design

#3128 Misc fixes
  core/classes/Group_Sync/GroupSyncManager.php
  core/classes/Misc/HttpUtils.php
  core/classes/Misc/Text.php
  core/installation/steps/admin_account_setup.php
  core/installation/steps/database_configuration.php
  custom/templates/DefaultRevamp/template.php
  modules/Core/pages/login.php
  modules/Core/queries/admin_users.php
  modules/Forum/classes/Forum.php
  modules/Forum/pages/forum/delete_post.php
  modules/Forum/pages/forum/merge.php
  modules/Forum/pages/forum/move.php
  modules/Forum/pages/forum/spam.php
  phpstan.neon
Labels: bug

#3181 Make sure integration verify code is not null
  modules/Core/classes/Integrations/MinecraftIntegration.php
Labels: bug

#3182 Allow setting `Helo` and `Hostname` values explicitly for emails
  core/classes/Core/Email.php
Labels: bug

#3183 Fix footer with CSS to remove flicker on each page load
  custom/templates/DefaultRevamp/css/custom.css
  custom/templates/DefaultRevamp/footer.tpl
  custom/templates/DefaultRevamp/js/scripts.js
  custom/templates/DefaultRevamp/template.php
  modules/Core/module.php
Labels: design

#3188 Revert "Fix footer with CSS to remove flicker on each page load"
  custom/templates/DefaultRevamp/css/custom.css
  custom/templates/DefaultRevamp/footer.tpl
  custom/templates/DefaultRevamp/js/scripts.js
  custom/templates/DefaultRevamp/template.php
  modules/Core/module.php
Labels: bug

#3186 Fix fallback to default template dark mode option
  core/migrations/20230114124352_users_night_mode_nullable.php
Labels: bug

#3194 Remove group sync info from user info endpoint
  core/classes/Core/Util.php
  modules/Core/includes/endpoints/GroupInfoEndpoint.php
  modules/Core/includes/endpoints/UserInfoEndpoint.php
Labels: enhancement, discussion

#3176 Fix post editing
  modules/Forum/classes/Forum.php
  modules/Forum/pages/forum/edit.php
Labels: bug

#3200 Allow running release script without TTY
  dev/scripts/release-entrypoint.sh
  dev/scripts/release.py
  release.sh
Labels: bug

#3205 Properly exclude node cache from releaes zips
  dev/scripts/release.py
Labels: bug

#3201 PHPDoc: Use debian image and speed up build
  .dockerignore
  Dockerfile.phpdoc
  dev/scripts/release.py
Labels: enhancement

#3193 Add groups parameter to list users endpoint
  modules/Core/includes/endpoints/ListUsersEndpoint.php
Labels: enhancement

#3197 Ignore future dates in dashboard overview graph data
  modules/Core/module.php
  modules/Forum/module.php
Labels: bug, design

#3202 Check for pdo_mysql extension, mysqli is no longer used
  core/installation/steps/requirements_validation.php
  modules/Core/pages/panel/index.php
Labels: enhancement

#3196 Remove panel template "Find Templates" section
  custom/languages/en_UK.json
  custom/panel_templates/Default/core/panel_templates.tpl
  modules/Core/pages/panel/panel_templates.php
Labels: enhancement

#3199 Allow selecting timezone during install
  core/classes/Database/DatabaseInitialiser.php
  core/installation/steps/admin_account_setup.php
  core/installation/steps/site_configuration.php
  custom/languages/en_UK.json
  dev/scripts/cli_install.php
Labels: enhancement

#3206 Fix forum post seeder not filling some columns
  dev/scripts/seeder/ForumPostSeeder.php
Labels: bug

#3218 Swap API URL and API key fields
  custom/panel_templates/Default/core/api.tpl
Labels: enhancement

#3217 Add X-API-Key fallback header if Authorization is missing
  core/classes/Endpoints/KeyAuthEndpoint.php
  docker-compose.yaml
Labels: enhancement

#3198 AuthMe improvements and fixes
  core/classes/Core/User.php
  core/classes/DTO/UserData.php
  core/classes/Database/DatabaseInitialiser.php
  core/includes/updates/202.php
  core/installation/includes/upgrade_perform.php
  core/migrations/20230121015140_add_auth_me_columns_to_user_table.php
  custom/languages/en_UK.json
  custom/panel_templates/Default/integrations/minecraft/minecraft_authme.tpl
  custom/panel_templates/Default/integrations/minecraft/placeholders.tpl
  custom/templates/DefaultRevamp/authme.tpl
  custom/templates/DefaultRevamp/authme_email.tpl
  custom/templates/DefaultRevamp/user/settings.tpl
  modules/Core/module.php
  modules/Core/pages/authme_connector.php
  modules/Core/pages/login.php
  modules/Core/pages/panel/minecraft.php
  modules/Core/pages/panel/minecraft_authme.php
  modules/Core/pages/user/settings.php
  modules/Core/queries/authme_test_connection.php
Labels: bug

#3203 Add support for automatically verifying emails from OAuth register
  core/classes/Misc/NamelessOAuth.php
  custom/languages/en_UK.json
  custom/templates/DefaultRevamp/register.tpl
  modules/Core/module.php
  modules/Core/pages/register.php
Labels: enhancement

#3221 Fix `Util::setSetting` cache not being updated
  core/classes/Core/Util.php
  modules/Core/pages/panel/minecraft.php
Labels: bug

#3223 Update server status page to refresh every 5 seconds
  custom/templates/DefaultRevamp/js/core/pages.js
Labels: enhancement

#3227 Properly encode content for javascript
  custom/templates/DefaultRevamp/template.php
Labels: bug

#3230 Use X-Real-IP header last
  core/classes/Misc/HttpUtils.php
Labels: bug

#3234 Make sure integration allow linking before forcing
  core/templates/frontend_init.php
Labels: bug

#3233 Create upgrade zip before installing development dependencies
  dev/scripts/release.py
Labels: bug

#3222 Rewrite Discord group sync to use v5 Nameless-Link API
  core/classes/Core/Log.php
  core/classes/Group_Sync/BatchableGroupSyncInjector.php
  core/classes/Group_Sync/GroupSyncManager.php
  custom/languages/en_UK.json
  modules/Core/classes/Group_Sync/MinecraftGroupSyncInjector.php
  modules/Core/classes/Misc/CoreApiErrors.php
  modules/Core/includes/endpoints/ServerInfoEndpoint.php
  modules/Core/includes/endpoints/UpdateGroupsEndpoint.php
  modules/Discord Integration/classes/Discord.php
  modules/Discord Integration/classes/DiscordGroupSyncInjector.php
  modules/Discord Integration/pages/panel/discord.php
Labels: bug

#3238 Use correct source directory
  dev/scripts/release.py
Labels: bug

#3242 Update contributing documentation to mention npm
  CONTRIBUTING.md
Labels: meta
