Repository NamelessMC/Nameless, pull requests merged in 2023-04, with the labels that each got.

#3285 Add support to customize OAuth login buttons
  core/assets/img/google_logo.png
  core/classes/Misc/NamelessOAuth.php
  custom/languages/en_UK.json
  custom/panel_templates/Default/core/registration.tpl
  custom/templates/DefaultRevamp/login.tpl
  custom/templates/DefaultRevamp/register.tpl
  modules/Core/module.php
  modules/Core/pages/login.php
  modules/Core/pages/panel/registration.php
  modules/Core/pages/register.php
Labels: bug, enhancement

#3308 Use regex to determine which files to treat as migration files
  core/classes/Database/PhinxAdapter.php
Labels: bug

#3309 Better handling of closures in exception frames
  core/classes/Misc/ErrorHandler.php
Labels: bug

#3303 Add ability to customise number of news items on front page
  core/classes/Core/Validate.php
  custom/panel_templates/Default/forum/forums_settings.tpl
  dev/phpstan.neon
  modules/Forum/front_page.php
  modules/Forum/language/en_UK.json
  modules/Forum/pages/panel/settings.php
Labels: enhancement

#3281 Create `HasWebhookParams` interface
  core/classes/Events/DiscordDispatchable.php
  core/classes/Events/EventHandler.php
  core/classes/Events/HasWebhookParams.php
  core/classes/Events/WebhookDispatcher.php
  custom/languages/en_UK.json
  custom/panel_templates/Default/core/hooks_edit.tpl
  custom/panel_templates/Default/core/hooks_new.tpl
  dev/scripts/cli_install.php
  modules/Core/classes/Events/AnnouncementCreatedEvent.php
  modules/Core/classes/Events/ReportCreatedEvent.php
  modules/Core/classes/Events/UserBannedEvent.php
  modules/Core/classes/Events/UserDeletedEvent.php
  modules/Core/classes/Events/UserGroupAddedEvent.php
  modules/Core/classes/Events/UserGroupRemovedEvent.php
  modules/Core/classes/Events/UserIntegrationLinkedEvent.php
  modules/Core/classes/Events/UserIntegrationUnlinkedEvent.php
  modules/Core/classes/Events/UserIntegrationVerifiedEvent.php
  modules/Core/classes/Events/UserProfilePostCreatedEvent.php
  modules/Core/classes/Events/UserProfilePostReplyCreatedEvent.php
  modules/Core/classes/Events/UserRegisteredEvent.php
  modules/Core/classes/Events/UserValidatedEvent.php
  modules/Core/classes/Events/UserWarnedEvent.php
  modules/Core/hooks/WebHook.php
  modules/Core/pages/panel/hooks.php
  modules/Discord Integration/hooks/DiscordHook.php
  modules/Forum/classes/Events/TopicCreatedEvent.php
  modules/Forum/classes/Events/TopicReplyCreatedEvent.php
  modules/Forum/language/en_UK.json
  modules/Forum/pages/forum/new_topic.php
  modules/Forum/pages/forum/view_topic.php
Labels: bug

#3171 Don't decode before encoding for new installations
  core/classes/Core/Output.php
Labels: bug

#3316 Do not encode welcome post
  core/classes/Database/DatabaseInitialiser.php
Labels: bug

#3324 Use relative paths so phpdoc treats it as a single docset
  Dockerfile.phpdoc
Labels: bug

#3159 Integrity checking system
  .gitignore
  core/classes/Misc/IntegrityChecker.php
  dev/scripts/generate_checksums.php
  dev/scripts/release.py
  dev/scripts/verify_checksums.php
Labels: enhancement

#3224 Replace manual queries with util setting functions
  custom/languages/en_UK.json
  modules/Core/pages/login.php
  modules/Core/pages/panel/api.php
  modules/Core/pages/panel/general_settings.php
  modules/Core/pages/panel/minecraft_authme.php
  modules/Core/pages/panel/privacy_and_terms.php
  modules/Core/pages/panel/registration.php
  modules/Core/pages/register.php
  modules/Core/pages/terms.php
Labels: bug

#3326 Allow correct webhook action types in endpoint
  modules/Core/includes/endpoints/CreateWebhooksEndpoint.php
Labels: bug

#3330 Fix default user template setting
  custom/templates/DefaultRevamp/user/settings.tpl
  modules/Core/pages/panel/users_edit.php
  modules/Core/pages/user/settings.php
Labels: bug
