Repository NamelessMC/Nameless, pull requests merged in 2023-10, with the labels that each got.

#3446 Restore npm install call in release script
  dev/scripts/release.py
Labels: bug

#3431 Add forum description variable
  modules/Forum/pages/forum/view_forum.php
Labels: enhancement, design

#3422 Add default page description & keywords
  core/templates/frontend_init.php
  custom/languages/en_UK.json
  custom/panel_templates/Default/core/seo.tpl
  modules/Core/pages/panel/seo.php
Labels: enhancement
