Repository NamelessMC/Nameless, pull requests merged in 2024-12, with the labels that each got.

#3558 Add PHP 8.4 to pipelines
  .github/workflows/ci.yml
Labels: meta

#3560 Fix being unable to centre images via editor
  core/classes/Core/Output.php
Labels: bug

#3561 Sync dark mode between panel and frontend
  core/templates/backend_init.php
  custom/panel_templates/Default/index.tpl
  custom/panel_templates/Default/navbar.tpl
  custom/panel_templates/Default/scripts.tpl
  custom/panel_templates/Default/template.php
Labels: enhancement

#3562 Fix misleading error logging in if the user is banned
  modules/Core/pages/login.php
Labels: bug

#3557 Permissions for posting on profiles
  core/classes/Database/DatabaseInitialiser.php
  custom/templates/DefaultRevamp/css/custom.css
  custom/templates/DefaultRevamp/profile.tpl
  modules/Core/language/en_UK.json
  modules/Core/module.php
  modules/Core/pages/profile.php
Labels: enhancement

#3559 Add ability to re-order placeholders
  core/classes/Misc/Placeholders.php
  core/migrations/20241201113419_add_placeholder_order_to_placeholder_settings_table.php
  custom/panel_templates/Default/integrations/minecraft/placeholders.tpl
  custom/panel_templates/Default/template.php
  custom/templates/DefaultRevamp/css/custom.css
  custom/templates/DefaultRevamp/leaderboards.tpl
  modules/Core/language/en_UK.json
  modules/Core/pages/leaderboards.php
  modules/Core/pages/panel/placeholders.php
Labels: enhancement

#3525 Add queue task to purge inactive users
  core/includes/updates/212.php
  custom/panel_templates/Default/core/registration.tpl
  modules/Core/classes/Tasks/PurgeInactiveUsers.php
  modules/Core/language/en_UK.json
  modules/Core/pages/panel/registration.php
Labels: enhancement

#3569 Fix users being able to bypass email verification
  core/classes/Core/Validate.php
Labels: bug
