Repository NamelessMC/Nameless, pull requests merged in 2024-06, with the labels that each got.

#3449 Add uninstall option to modules
  core/classes/Core/Util.php
  custom/panel_templates/Default/core/modules.tpl
  modules/Core/language/en_UK.json
  modules/Core/pages/panel/modules.php
Labels: enhancement

#3497 Array map require array
  core/classes/Events/DiscordWebhookBuilder.php
Labels: bug

#3519 Add Persian (Iran) langauge
  core/classes/Core/Language.php
  dev/scripts/create_lang.py
  modules/Cookie Consent/language/fa_IR.json
  modules/Core/language/fa_IR.json
  modules/Discord Integration/language/fa_IR.json
  modules/Forum/language/fa_IR.json
  modules/Members/language/fa_IR.json
Labels: translation
